export default {
  user: {
    USER_SEARCH_REQUEST: 'USER_SEARCH_REQUEST',
    USER_SEARCH_SUCCESS: 'USER_SEARCH_SUCCESS',
    USER_SEARCH_FAILURE: 'USER_SEARCH_FAILURE',
    USER_SEARCH_CLEAR_RESULTS: 'USER_SEARCH_CLEAR_RESULTS',

    USER_GET_REQUEST: 'USER_GET_REQUEST',
    USER_GET_SUCCESS: 'USER_GET_SUCCESS',
    USER_GET_FAILURE: 'USER_GET_FAILURE',

    USER_GET_REPOS_REQUEST: 'USER_GET_REPOS_REQUEST',
    USER_GET_REPOS_SUCCESS: 'USER_GET_REPOS_SUCCESS',
    USER_GET_REPOS_FAILURE: 'USER_GET_REPOS_FAILURE',

  },
  localStorage: {
    LOCALSTORAGE_SET_REQUEST: "LOCALSTORAGE_SET_REQUEST",
    LOCALSTORAGE_SET_SUCCESS: "LOCALSTORAGE_SET_SUCCESS",
    LOCALSTORAGE_SET_FAILURE: "LOCALSTORAGE_SET_FAILURE",

    LOCALSTORAGE_GET_REQUEST: "LOCALSTORAGE_GET_REQUEST",
    LOCALSTORAGE_GET_SUCCESS: "LOCALSTORAGE_GET_SUCCESS",
    LOCALSTORAGE_GET_FAILURE: "LOCALSTORAGE_GET_FAILURE",

    LOCALSTORAGE_REM_REQUEST: "LOCALSTORAGE_REM_REQUEST",
    LOCALSTORAGE_REM_SUCCESS: "LOCALSTORAGE_REM_SUCCESS",
    LOCALSTORAGE_REM_FAILURE: "LOCALSTORAGE_REM_FAILURE",

  }
};